name: Build & Publish Image

on:
  push:
    tags: [ "v*.**" ]
    branches:
    - main

env:
  IMAGE_NAME: qbittorrent-exporter
  IMAGE_TAGS: ${{ github.ref_name }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
        
    - name: Build Image
      id: build-tag
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ github.ref_name }}
        oci: true
        containerfiles: |
          ./Containerfile
    
    - name: Publish Image
      id: publish-tag
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-tag.outputs.image }}
        tags: ${{ steps.build-tag.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASSWORD }}
        extra-args: |
          --disable-content-trust
    
    - name: Output Image Location
      run: echo "Image published to ${{ steps.publish.outputs.registry-paths }}"
